name: CICD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - devel

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  swagger:
    name: Swagger Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate Swagger Specs
        run: make swagger.gen
      
      - name: Validate Swagger Specs
        run: make swagger.validate

